# Generated by Django 5.2 on 2025-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_review_date_posted_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
